{% set name = "logging_tree" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd78848fe0ee4aafcc64fa8a66f96f177186ff3d883619b1d7f3628564802095

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - logging_tree

about:
  home: https://github.com/brandon-rhodes/logging_tree
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: Introspect and display the logger tree inside "logging"

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
